# Generated by Django 3.0.3 on 2020-09-26 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='タグ名')),
            ],
            options={
                'db_table': 'hashtag',
            },
        ),
        migrations.CreateModel(
            name='TweetTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='テンプレート名')),
                ('content', models.TextField(blank=True, max_length=1000, verbose_name='本文')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rank', models.IntegerField(default=-1, verbose_name='順位')),
            ],
            options={
                'db_table': 'tweet_template',
            },
        ),
    ]
